name: Thử nghiệm đọc file README #tên quy trình

on:
  push:
    branches: ["main"]
jobs:
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: Bước 1 - Xin chào
        run: echo "Hello World!" #lệnh in ra màn hình
        
      - name: Bước 2 - Tải code
        uses: actions/checkout@v6.0.2 #Robot tự động copy code vào máy ảo
        
      - name: Bước 3 - Đọc file
        run: cat README.md #mở rộng nội dung file README.md để xem
